Repository softlayer/softlayer-python, pull requests merged in 2019-11, with the labels that each got.

#1182 Fixed vs reboot unable to resolve vs names
  SoftLayer/CLI/virt/power.py
  SoftLayer/transports.py
  tests/CLI/modules/autoscale_tests.py
Labels: CLI

#1184 Fix python misspelling
  README.rst
Labels: Documentation

#1188 Version to 5.8.2
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release
