Repository softlayer/softlayer-python, pull requests merged in 2019-05, with the labels that each got.

#1140 5.7.2
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
  snap/snapcraft.yaml
Labels: Core

#1146 Docs - replace broken 'developer' links with 'sldn'
  README.rst
  SoftLayer/managers/ssl.py
  docs/api/client.rst
Labels: Documentation

#1143 Upgrade to prompt_toolkit >= 2
  README.rst
  SoftLayer/shell/completer.py
  SoftLayer/shell/core.py
  SoftLayer/testing/__init__.py
  setup.py
  tests/CLI/modules/shell_tests.py
  tools/requirements.txt
  tools/test-requirements.txt
Labels: CLI

#1148 Remove contents from the new_ticket object and unittests
  SoftLayer/managers/ticket.py
  tests/CLI/modules/ticket_tests.py
  tests/managers/ticket_tests.py
Labels: Bug
