Repository softlayer/softlayer-python, pull requests merged in 2019-10, with the labels that each got.

#1177 Autoscale
  README.rst
  SoftLayer/CLI/autoscale/__init__.py
  SoftLayer/CLI/autoscale/detail.py
  SoftLayer/CLI/autoscale/edit.py
  SoftLayer/CLI/autoscale/list.py
  SoftLayer/CLI/autoscale/logs.py
  SoftLayer/CLI/autoscale/scale.py
  SoftLayer/CLI/autoscale/tag.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Scale_Group.py
  SoftLayer/fixtures/SoftLayer_Scale_Policy.py
  SoftLayer/managers/autoscale.py
  docs/api/managers/autoscale.rst
  docs/cli/autoscale.rst
  tests/CLI/modules/autoscale_tests.py
  tests/managers/autoscale_tests.py
Labels: CLI

#1178 #962 fixed image list in rest
  SoftLayer/CLI/image/list.py
Labels: Bug

#1180 v5.8.1
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
  snap/snapcraft.yaml
Labels: CLI

#1179 #1095 Handle missing fixtures better in unit tests.
  SoftLayer/testing/__init__.py
  SoftLayer/testing/xmlrpc.py
  tests/CLI/modules/call_api_tests.py
Labels: Core
