Repository softlayer/softlayer-python, pull requests merged in 2020-01, with the labels that each got.

#1208 Functionality for VolumeLimit per DataCenter
  SoftLayer/CLI/block/limit.py
  SoftLayer/CLI/file/limit.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  SoftLayer/managers/block.py
  SoftLayer/managers/file.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/file_tests.py
  tests/managers/block_tests.py
  tests/managers/cdn_tests.py
  tests/managers/file_tests.py
  tests/managers/ordering_tests.py
Labels: CLI

#1209 Add testing/CI for python 3.8
  .travis.yml
  README.rst
  setup.py
  tox.ini
Labels: Core

#1213 Fix vs detail.
  SoftLayer/CLI/virt/detail.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/vs/vs_tests.py
Labels: Bug

#1218 fix the issue 1217 about globalip create ipv6
  SoftLayer/CLI/globalip/create.py
Labels: Bug

#1216 1211 REST Issues: file replica-order fails
  SoftLayer/managers/storage_utils.py
Labels: Bug

#1214 issue#1210 file block storage - adding new feature to list, assign, a…
  SoftLayer/CLI/block/subnets/__init__.py
  SoftLayer/CLI/block/subnets/assign.py
  SoftLayer/CLI/block/subnets/list.py
  SoftLayer/CLI/block/subnets/remove.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Storage_Allowed_Host.py
  SoftLayer/managers/block.py
  tests/CLI/modules/block_tests.py
  tests/managers/block_tests.py
Labels: CLI

#1219 Doc updates
  SoftLayer/CLI/metadata.py
  SoftLayer/CLI/user/create.py
  SoftLayer/CLI/user/delete.py
  SoftLayer/CLI/user/edit_details.py
  SoftLayer/CLI/user/edit_permissions.py
  SoftLayer/managers/autoscale.py
  docs/cli.rst
  docs/cli/block.rst
  docs/cli/call_api.rst
  docs/cli/cdn.rst
  docs/cli/commands.rst
  docs/cli/config.rst
  docs/cli/dedicated.rst
  docs/cli/dns.rst
  docs/cli/file.rst
  docs/cli/firewall.rst
  docs/cli/global_ip.rst
  docs/cli/hardware.rst
  docs/cli/image.rst
  docs/cli/loadbal.rst
  docs/cli/object_storage.rst
  docs/cli/rwhois.rst
  docs/cli/security_groups.rst
  docs/cli/sshkey.rst
  docs/cli/ssl.rst
  docs/cli/subnet.rst
  docs/cli/tickets.rst
  docs/cli/users.rst
  docs/cli/vlan.rst
  docs/cli/vs.rst
  docs/cli_directory.rst
  docs/dev/cli.rst
  docs/index.rst
Labels: Documentation

#1220 v5.8.5
  CHANGELOG.md
  SoftLayer/consts.py
  docs/cli/block.rst
  setup.py
Labels: Release
