Repository softlayer/softlayer-python, pull requests merged in 2020-11, with the labels that each got.

#1369 RWHOIS is deprecated, replace it or remove it.
  SoftLayer/CLI/registration/__init__.py
  SoftLayer/CLI/registration/detail.py
  SoftLayer/CLI/registration/show.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/rwhois/__init__.py
  SoftLayer/CLI/rwhois/edit.py
  SoftLayer/CLI/rwhois/show.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Network_Subnet_Registration.py
  SoftLayer/managers/network.py
  SoftLayer/managers/registration.py
  docs/cli.rst
  docs/cli/registration.rst
  docs/cli/rwhois.rst
  tests/CLI/modules/registration_tests.py
  tests/CLI/modules/rwhois_tests.py
  tests/managers/network_tests.py
Labels: Core

#1381 fixed analysis/flake8 tests
  tests/CLI/modules/config_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
Labels: Internal

#1377 Remove the `-a` option from `slcli user create`
  SoftLayer/CLI/user/create.py
  tests/CLI/modules/user_tests.py
Labels: CLI

#1376 RIR Contact list
  SoftLayer/CLI/registration/contacts.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/registration.py
  docs/cli/registration.rst
  tests/CLI/modules/registration_tests.py
Labels: New Feature

#1382 slcli registration person-edit
  SoftLayer/CLI/registration/person_edit.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/create.py
  SoftLayer/fixtures/SoftLayer_Account_Regional_Registry_Detail.py
  SoftLayer/fixtures/SoftLayer_Account_Regional_Registry_Detail_Property.py
  SoftLayer/managers/__init__.py
  SoftLayer/managers/network.py
  SoftLayer/managers/registration.py
  docs/api/managers/registration.rst
  docs/cli/registration.rst
  tests/CLI/modules/config_tests.py
  tests/CLI/modules/registration_tests.py
  tests/CLI/modules/user_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
Labels: New Feature

#1383 slcli registration person-detail
  SoftLayer/CLI/registration/person_detail.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account_Regional_Registry_Detail.py
  SoftLayer/managers/registration.py
  docs/cli/registration.rst
  tests/CLI/modules/registration_tests.py
  tests/managers/registration_tests.py
Labels: New Feature

#1384 Add pagination to block and file storage.
  SoftLayer/managers/block.py
  SoftLayer/managers/file.py
Labels: Storage
