Repository softlayer/softlayer-python, pull requests merged in 2020-10, with the labels that each got.

#1350 Add to block and file storage volume list order.
  SoftLayer/CLI/block/list.py
  SoftLayer/CLI/block/order.py
  SoftLayer/CLI/file/list.py
  SoftLayer/CLI/file/order.py
  SoftLayer/managers/block.py
  SoftLayer/managers/file.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/file_tests.py
  tests/managers/block_tests.py
  tests/managers/file_tests.py
Labels: Storage

#1351 Add prices to vs create-options.
  SoftLayer/CLI/virt/create_options.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/hardware_tests.py
  tests/managers/vs/vs_tests.py
Labels: Ordering

#1359 remove the zeros(0) in the list.
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  tests/CLI/modules/server_tests.py
Labels: Ordering

#1353 remove the zeros(0) in the list.
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  tests/CLI/modules/server_tests.py
Labels: Ordering

#1356 Allow orders without a location if needed
  SoftLayer/CLI/order/place.py
  SoftLayer/CLI/ticket/create.py
  SoftLayer/CLI/ticket/update.py
  SoftLayer/managers/ordering.py
  docs/cli/block.rst
  docs/cli/file.rst
  docs/cli/tickets.rst
  tests/managers/ordering_tests.py
Labels: Ordering

#1357 Refactor file and block commands to use the username resolver
  SoftLayer/CLI/block/access/list.py
  SoftLayer/CLI/block/snapshot/list.py
  SoftLayer/CLI/block/subnets/list.py
  SoftLayer/CLI/file/access/list.py
  SoftLayer/CLI/file/snapshot/list.py
Labels: Storage

#1354 Order lookup
  SoftLayer/CLI/account/invoice_detail.py
  SoftLayer/CLI/account/orders.py
  SoftLayer/CLI/order/lookup.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Billing_Order.py
  SoftLayer/managers/ordering.py
  docs/cli/ordering.rst
  tests/CLI/modules/order_tests.py
  tests/managers/ordering_tests.py
Labels: Ordering

#1361 Updated snapcraft.yaml
  snap/snapcraft.yaml
Labels: Core

#1363 moved snapcraft readme
  README-snapcraft.md
Labels: Core

#1364 Snapcraft
  snap/snapcraft.yaml
Labels: Core

#1366 Updated documentation on how to deal with KeyError
  docs/api/client.rst
Labels: Documentation

#1365 Update snapcraft.yaml
  snap/snapcraft.yaml
Labels: Core

#1360 Fix order item-list --prices location
  SoftLayer/CLI/order/item_list.py
  SoftLayer/managers/ordering.py
  tests/CLI/modules/order_tests.py
  tests/managers/ordering_tests.py
Labels: Ordering

#1368 Removed Nessus scanner from docs and examples
  SoftLayer/CLI/order/place.py
  SoftLayer/CLI/order/place_quote.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  docs/cli/ordering.rst
  docs/cli/vs.rst
Labels: Core
