Repository softlayer/softlayer-python, pull requests merged in 2020-09, with the labels that each got.

#1342 for implementing FBLOCK-3470
  SoftLayer/CLI/block/refresh.py
  SoftLayer/CLI/file/refresh.py
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  SoftLayer/managers/storage.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/file_tests.py
  tests/managers/block_tests.py
  tests/managers/file_tests.py
Labels: Storage

#1344 v5.9.1 changelog
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1319 Ordering price information improvements.
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/CLI/order/item_list.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/hardware.py
  SoftLayer/managers/ordering.py
  tests/CLI/modules/order_tests.py
  tests/CLI/modules/server_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
  tests/managers/hardware_tests.py
  tests/managers/ordering_tests.py
Labels: CLI, Ordering

#1337 refactor vsi create-option
  SoftLayer/CLI/virt/create_options.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/vs/vs_tests.py
Labels: Ordering

#1338 #1336 add Invoice Item id as param valid in account item-detail command
  SoftLayer/CLI/account/item_detail.py
  SoftLayer/fixtures/SoftLayer_Billing_Invoice_Item.py
  SoftLayer/managers/account.py
  tests/managers/account_tests.py
Labels: Ordering

#1349 slcli account orders
  SoftLayer/CLI/account/orders.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Billing_Order.py
  SoftLayer/managers/account.py
  docs/cli/account.rst
  tests/CLI/modules/account_tests.py
Labels: Ordering
