Repository softlayer/softlayer-python, pull requests merged in 2020-07, with the labels that each got.

#1291 Removed overly specific reference to Block storage
  SoftLayer/managers/storage.py
  tests/managers/block_tests.py
Labels: Documentation

#1293 add system operation referenceCode in create-option
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/managers/hardware.py
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI, Ordering

#1290 Add functionality to order a hw for capacityRestrictionType PROCCESOR.
  SoftLayer/managers/ordering.py
  tests/managers/ordering_tests.py
Labels: Bug, Ordering

#1294 v5.8.9 release notes
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1297 Notification management
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/edit_notifications.py
  SoftLayer/CLI/user/notifications.py
  SoftLayer/fixtures/SoftLayer_Email_Subscription.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: New Feature

#1296 `slcli hw create` updates
  SoftLayer/CLI/formatting.py
  SoftLayer/CLI/hardware/create.py
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/managers/hardware.py
  docs/cli/hardware.rst
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI, Ordering

#1303 #1298 Fix Unhandled exception in CLI - vs detail
  SoftLayer/CLI/virt/detail.py
  SoftLayer/CLI/virt/storage.py
Labels: Bug

#1311 fix the empty lines
  SoftLayer/CLI/order/preset_list.py
Labels: Bug

#1306 List hardware vs associated.
  SoftLayer/CLI/hardware/guests.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/virt/list.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Hardware_Server.py
  SoftLayer/fixtures/SoftLayer_Virtual_Host.py
  SoftLayer/managers/hardware.py
  SoftLayer/managers/vs.py
  docs/cli/hardware.rst
  tests/CLI/modules/server_tests.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/hardware_tests.py
  tests/managers/vs/vs_tests.py
Labels: CLI

#1307 #875 added option to reload bare metal servers with LVM enabled
  SoftLayer/CLI/hardware/reload.py
  SoftLayer/managers/hardware.py
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI

#1304 Added Migrate command
  SoftLayer/CLI/dedicatedhost/detail.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/virt/migrate.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/managers/vs.py
  SoftLayer/testing/__init__.py
  docs/cli/vs.rst
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/vs/vs_tests.py
Labels: New Feature

#1312 fixed vs_tests
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug

#1313 added support for filteredMask
  SoftLayer/transports.py
  tests/transport_tests.py
Labels: Core

#1314 #1305 Update docs links
  CHANGELOG.md
  SoftLayer/CLI/block/order.py
  SoftLayer/CLI/file/order.py
  SoftLayer/CLI/image/export.py
  SoftLayer/CLI/image/import.py
  SoftLayer/managers/block.py
  SoftLayer/managers/dns.py
  SoftLayer/managers/firewall.py
  SoftLayer/managers/hardware.py
  SoftLayer/managers/image.py
  SoftLayer/managers/network.py
  SoftLayer/managers/object_storage.py
  SoftLayer/managers/ssl.py
  SoftLayer/managers/ticket.py
  SoftLayer/managers/vs.py
  SoftLayer/managers/vs_capacity.py
  docs/cli/vs/reserved_capacity.rst
Labels: Documentation

#1310 #1302 fix lots of whitespace slcli vs create-options
  SoftLayer/CLI/virt/create_options.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug
