Repository softlayer/softlayer-python, pull requests merged in 2021-08, with the labels that each got.

#1523 fix the network space is empty on subnet detail
  SoftLayer/CLI/subnet/detail.py
Labels: CLI

#1527 Prevents SLCLI_VERSION environment variable from breaking things
  .github/workflows/release.yml
  README.rst
  SoftLayer/CLI/core.py
Labels: CLI

#1521 Refactor loadbal order-options
  SoftLayer/CLI/loadbal/order.py
  tests/CLI/modules/loadbal_tests.py
Labels: CLI, Ordering

#1526 slcli server create-options dal13 Error
  SoftLayer/CLI/hardware/create_options.py
  SoftLayer/managers/account.py
  tests/managers/account_tests.py
Labels: Bug, Ordering

#1528 v5.9.7 changelog
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1534 Fix code blocks formatting of The Solution section docs
  docs/api/client.rst
Labels: Bug, Documentation

#1535 Add retry decorator to documentation
  docs/api/client.rst
Labels: Bug, Documentation

#1536 Issues/1532 utility docs
  SoftLayer/utils.py
  docs/api/client.rst
Labels: Bug, Documentation

#1537 Add Exceptions to Documentation
  docs/api/client.rst
Labels: Bug, Documentation
