Repository softlayer/softlayer-python, pull requests merged in 2021-11, with the labels that each got.

#1557 Update API docs link and remove travisCI mention
  docs/dev/index.rst
Labels: Documentation

#1554 Snapshot notify
  SoftLayer/CLI/block/snapshot/get_notify_status.py
  SoftLayer/CLI/block/snapshot/set_notify_status.py
  SoftLayer/CLI/file/snapshot/get_notify_status.py
  SoftLayer/CLI/file/snapshot/set_notify_status.py
  SoftLayer/CLI/routes.py
  SoftLayer/managers/storage.py
  docs/cli/block.rst
  docs/cli/file.rst
Labels: CLI, New Feature

#1559 return error internal in vs usage feature when sent the valid-type in…
  SoftLayer/CLI/virt/usage.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug

#1563 Fix errors with `vs bandwidth`
  SoftLayer/CLI/virt/bandwidth.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug

#1564 Add Item names to vs billing report
  SoftLayer/CLI/virt/billing.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
Labels: CLI

#1565 Mapping is now in collections.abc
  SoftLayer/utils.py
Labels: Core

#1567 fix vs placementgroup list
  SoftLayer/CLI/virt/placementgroup/list.py
Labels: CLI
