Repository softlayer/softlayer-python, pull requests merged in 2021-06, with the labels that each got.

#1483 add new email feature
  SoftLayer/CLI/email/__init__.py
  SoftLayer/CLI/email/detail.py
  SoftLayer/CLI/email/edit.py
  SoftLayer/CLI/email/list.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Network_Message_Delivery_Email_Sendgrid.py
  SoftLayer/managers/account.py
  SoftLayer/managers/email.py
  docs/api/managers/email.rst
  docs/cli.rst
  docs/cli/email.rst
  tests/CLI/modules/email_tests.py
  tests/managers/email_tests.py
Labels: CLI, New Feature

#1488 Add a table result for the hw upgrade.
  SoftLayer/CLI/hardware/upgrade.py
  SoftLayer/fixtures/SoftLayer_Product_Order.py
  SoftLayer/fixtures/SoftLayer_Provisioning_Maintenance_Window.py
  SoftLayer/managers/hardware.py
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI

#1497 Remove block/file interval option for replica volume.
  SoftLayer/CLI/block/replication/order.py
  SoftLayer/CLI/file/replication/order.py
Labels: Storage

#1495 slcli vlan cancel should report if a vlan is automatic
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/vlan/cancel.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan.py
  SoftLayer/managers/network.py
  docs/cli/vlan.rst
  tests/CLI/modules/vlan_tests.py
Labels: CLI

#1498 Add gateway/firewall name to vlan detail and list command
  SoftLayer/CLI/vlan/detail.py
  SoftLayer/CLI/vlan/list.py
  SoftLayer/managers/network.py
  tests/CLI/modules/vlan_tests.py
Labels: Bug

#1501 Add slcli account licenses
  SoftLayer/CLI/account/licenses.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/account.py
  docs/cli/account.rst
  tests/CLI/modules/account_tests.py
  tests/managers/account_tests.py
Labels: New Feature

#1506 new method to fix the table disconfigurate when the text data is very…
  SoftLayer/utils.py
Labels: Core
