Repository softlayer/softlayer-python, pull requests merged in 2021-05, with the labels that each got.

#1459 Add an --orderBy parameters to call-api
  SoftLayer/CLI/call_api.py
  SoftLayer/utils.py
  tests/CLI/modules/call_api_tests.py
Labels: Core

#1475 add the firewall information on slcli firewall detail
  SoftLayer/CLI/firewall/detail.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan_Firewall.py
  SoftLayer/managers/firewall.py
  tests/CLI/modules/firewall_tests.py
Labels: CLI

#1470 Show component versions on hw detail
  SoftLayer/CLI/hardware/detail.py
  SoftLayer/fixtures/SoftLayer_Hardware_Server.py
  SoftLayer/managers/hardware.py
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI

#1487 #1486 fixed newly failing unit tests
  SoftLayer/CLI/virt/create.py
  tests/CLI/modules/vs/vs_create_tests.py
  tests/api_tests.py
Labels: Bug

#1484 Fix Incomplete notes field for file and block
  SoftLayer/CLI/block/list.py
  SoftLayer/CLI/environment.py
  SoftLayer/CLI/file/list.py
  SoftLayer/CLI/storage_utils.py
  tests/CLI/environment_tests.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/file_tests.py
Labels: Bug

#1493 v5.9.5 updates
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1494 Updated snap to core20 and edited README
  README.rst
  snap/snapcraft.yaml
Labels: Core
