Repository softlayer/softlayer-python, pull requests merged in 2021-09, with the labels that each got.

#1543 Forces specific endoing on XMLRPC requests
  SoftLayer/CLI/autoscale/__init__.py
  SoftLayer/CLI/autoscale/edit.py
  SoftLayer/CLI/block/count.py
  SoftLayer/CLI/block/replication/partners.py
  SoftLayer/CLI/dns/zone_import.py
  SoftLayer/CLI/file/count.py
  SoftLayer/CLI/file/replication/partners.py
  SoftLayer/CLI/firewall/edit.py
  SoftLayer/CLI/hardware/edit.py
  SoftLayer/CLI/hardware/upgrade.py
  SoftLayer/CLI/order/quote.py
  SoftLayer/CLI/sshkey/add.py
  SoftLayer/CLI/sshkey/print.py
  SoftLayer/CLI/ssl/add.py
  SoftLayer/CLI/ssl/download.py
  SoftLayer/CLI/ssl/edit.py
  SoftLayer/CLI/storage_utils.py
  SoftLayer/CLI/template.py
  SoftLayer/CLI/virt/create.py
  SoftLayer/CLI/virt/edit.py
  SoftLayer/CLI/virt/upgrade.py
  SoftLayer/config.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/vs_capacity.py
  SoftLayer/transports.py
  tests/transport_tests.py
Labels: Core

#1544 Add sensor data to hardware
  SoftLayer/CLI/hardware/sensor.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Hardware.py
  SoftLayer/managers/hardware.py
  docs/cli/hardware.rst
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: New Feature

#1548 Ignoring f-string related messages for tox for now
  tox.ini
Labels: Bug

#1546 Fix account events
  SoftLayer/CLI/account/events.py
  tests/CLI/modules/account_tests.py
Labels: Bug

#1549 Issues/1541 loadbal details
  SoftLayer/CLI/loadbal/detail.py
  SoftLayer/fixtures/SoftLayer_Network_LBaaS_LoadBalancer.py
  SoftLayer/managers/load_balancer.py
  tests/CLI/modules/loadbal_tests.py
Labels: New Feature
