Repository softlayer/softlayer-python, pull requests merged in 2021-07, with the labels that each got.

#1510 Fix Tox-analysis issues.
  SoftLayer/CLI/block/count.py
  SoftLayer/CLI/core.py
  SoftLayer/CLI/file/count.py
  SoftLayer/CLI/formatting.py
  SoftLayer/CLI/loadbal/detail.py
  SoftLayer/CLI/loadbal/pools.py
  SoftLayer/CLI/ssl/add.py
  SoftLayer/CLI/ssl/edit.py
  SoftLayer/CLI/template.py
  SoftLayer/CLI/virt/bandwidth.py
  SoftLayer/utils.py
Labels: Core

#1504 create a new commands on slcli that create/cancel a VMware licenses s…
  SoftLayer/CLI/licenses/__init__.py
  SoftLayer/CLI/licenses/cancel.py
  SoftLayer/CLI/licenses/create.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Product_Order.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/fixtures/SoftLayer_Software_AccountLicense.py
  SoftLayer/managers/__init__.py
  SoftLayer/managers/license.py
  docs/cli/licenses.rst
  tests/CLI/modules/licenses_test.py
Labels: New Feature

#1511 5.9.6 change log and updates
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1508 new feature licenses create-options
  SoftLayer/CLI/licenses/create_options.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/licenses.py
  docs/cli/licenses.rst
  tests/CLI/modules/licenses_test.py
Labels: New Feature, Ordering

#1513 Fixed some doc block issues when generating HTML
  SoftLayer/API.py
  SoftLayer/managers/hardware.py
Labels: Documentation

#1514 Updates to the Release workflow for publishing to test pypi
  .github/workflows/release.yml
  .github/workflows/test_pypi_release.yml
Labels: Core

#1499 add new feature on vlan cli
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/vlan/create.py
  SoftLayer/fixtures/SoftLayer_Network_Pod.py
  SoftLayer/fixtures/SoftLayer_Product_Order.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/network.py
  SoftLayer/utils.py
  docs/cli/vlan.rst
  tests/CLI/modules/vlan_tests.py
  tests/managers/network_tests.py
Labels: Ordering

#1502 Add the cdn edit option.
  SoftLayer/CLI/cdn/edit.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_CdnMarketplace_Configuration_Mapping.py
  SoftLayer/managers/cdn.py
  docs/cli/cdn.rst
  tests/CLI/modules/cdn_tests.py
  tests/managers/cdn_tests.py
Labels: New Feature

#1517 Adding in CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: Core

#1518 Create SECURITY.md
  SECURITY.md
Labels: Documentation
