Repository softlayer/softlayer-python, pull requests merged in 2022-08, with the labels that each got.

#1709 Command slcli vlan edit accept that we do not send any parameters
  SoftLayer/CLI/vlan/edit.py
Labels: Bug

#1713 Updated command - slcli vlan list
  SoftLayer/CLI/vlan/list.py
  SoftLayer/managers/network.py
Labels: New Feature

#1716 `slcli block subnets-list` command display an error message
  SoftLayer/CLI/block/subnets/list.py
Labels: Bug

#1717 add user remove-access command
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/remove_access.py
  SoftLayer/fixtures/SoftLayer_User_Customer.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: CLI

#1721 Add Devices with Trunks to vlan detail
  SoftLayer/CLI/vlan/detail.py
  SoftLayer/managers/network.py
Labels: New Feature

#1724 slcli hardware reflash-firmware command does not display success message
  SoftLayer/CLI/hardware/reflash_firmware.py
  tests/CLI/modules/server_tests.py
Labels: CLI

#1726 Fix bug with command - slcli cdn edit
  SoftLayer/CLI/cdn/edit.py
  SoftLayer/managers/cdn.py
Labels: Bug

#1734 v6.1.1 release notes
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: CLI

#1740 Snapcraft: Updated to Core22 and add homeishome-launch
  snap/snapcraft.yaml
Labels: Core

#1729 New command: ipsec cancel
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/vpn/ipsec/cancel.py
  SoftLayer/managers/ipsec.py
  docs/cli/ipsec.rst
  tests/CLI/modules/ipsec_tests.py
  tests/managers/ipsec_tests.py
Labels: CLI

#1738 New command: subnet clear-route
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/subnet/clear_route.py
  SoftLayer/fixtures/SoftLayer_Network_Subnet.py
  SoftLayer/managers/network.py
  docs/cli/subnet.rst
  tests/CLI/modules/subnet_tests.py
  tests/managers/network_tests.py
Labels: CLI

#1736 Deprecate slcli hw guests
  SoftLayer/CLI/hardware/guests.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Hardware_Server.py
  SoftLayer/managers/hardware.py
  docs/cli/hardware.rst
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI

#1743 Remove real usersnames from test fixtrues
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Network_Application_Delivery_Controller.py
  SoftLayer/fixtures/SoftLayer_Network_Storage_Hub_Cleversafe_Account.py
Labels: Bug

#1746 Fix tox request.get hangout issue
  SoftLayer/CLI/core.py
Labels: Bug
