Repository softlayer/softlayer-python, pull requests merged in 2022-06, with the labels that each got.

#1655 New command for getting duplicate convert status
  SoftLayer/CLI/block/duplicate_convert_status.py
  SoftLayer/CLI/file/duplicate_convert_status.py
  SoftLayer/CLI/routes.py
  SoftLayer/managers/storage.py
  docs/cli/block.rst
  docs/cli/file.rst
Labels: CLI, Storage

#1661 Fixed TOX errors
  SoftLayer/CLI/environment.py
  SoftLayer/auth.py
  SoftLayer/managers/account.py
  SoftLayer/managers/cdn.py
  SoftLayer/managers/dedicated_host.py
  SoftLayer/managers/email.py
  SoftLayer/managers/hardware.py
  SoftLayer/managers/ordering.py
  SoftLayer/managers/storage.py
  SoftLayer/managers/vs.py
  SoftLayer/managers/vs_capacity.py
  SoftLayer/managers/vs_placement.py
  SoftLayer/transports/__init__.py
  SoftLayer/transports/transport.py
  tox.ini
Labels: Bug

#1662 add a new feature to get all cloud object storage
  SoftLayer/CLI/block/object_list.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/block.py
  docs/cli/block.rst
  tests/CLI/modules/block_tests.py
  tests/managers/block_tests.py
Labels: New Feature

#1664 Update `slcli report bandwidth` command
  SoftLayer/CLI/report/bandwidth.py
  tests/CLI/modules/report_tests.py
Labels: Bug

#1657 add firewall monitoring command
  SoftLayer/CLI/firewall/monitoring.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan_Firewall.py
  SoftLayer/managers/firewall.py
  docs/cli/firewall.rst
  tests/CLI/modules/firewall_tests.py
  tests/managers/firewall_tests.py
Labels: New Feature

#1666 add a new command on block object-storage details
  SoftLayer/CLI/block/object_storage_detail.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  SoftLayer/managers/block.py
  docs/cli/block.rst
  tests/CLI/modules/block_tests.py
  tests/managers/block_tests.py
Labels: CLI

#1670 slcli account bandwidth-pools-detail command displays an error with b…
  SoftLayer/CLI/account/bandwidth_pools_detail.py
Labels: CLI

#1668 new feature block object-storage permissions command
  SoftLayer/CLI/block/object_storage_permission.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Storage_Hub_Cleversafe_Account.py
  SoftLayer/managers/storage.py
  docs/cli/block.rst
  tests/CLI/modules/block_tests.py
  tests/managers/block_tests.py
Labels: CLI

#1674 v6.1.0 Changelog and version bump
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release
