Repository softlayer/softlayer-python, pull requests merged in 2022-05, with the labels that each got.

#1628 new command on autoscale delete
  SoftLayer/CLI/autoscale/delete.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Scale_Group.py
  SoftLayer/managers/autoscale.py
  docs/cli/autoscale.rst
  tests/CLI/modules/autoscale_tests.py
  tests/managers/autoscale_tests.py
Labels: CLI, New Feature

#1629 Incorrect table title is displayed when an Auto Scale Group is scaled to reduce members
  SoftLayer/CLI/autoscale/scale.py
Labels: Bug

#1626 Soap transport
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Billing_Order.py
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/fixtures/SoftLayer_Software_AccountLicense.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/fixtures/soap/SoftLayer_Account_getObject.soap
  SoftLayer/fixtures/soap/SoftLayer_Account_getVirtualGuests.soap
  SoftLayer/fixtures/soap/SoftLayer_Virtual_Guest_getObject.soap
  SoftLayer/fixtures/soap/test_objectFilter.soap
  SoftLayer/fixtures/soap/test_objectMask.soap
  SoftLayer/managers/vs.py
  SoftLayer/transports.py
  SoftLayer/transports/__init__.py
  SoftLayer/transports/debug.py
  SoftLayer/transports/fixture.py
  SoftLayer/transports/rest.py
  SoftLayer/transports/soap.py
  SoftLayer/transports/timing.py
  SoftLayer/transports/transport.py
  SoftLayer/transports/xmlrpc.py
  tests/CLI/modules/server_tests.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/hardware_tests.py
  tests/transport_tests.py
  tests/transports/__init__.py
  tests/transports/debug_tests.py
  tests/transports/rest_tests.py
  tests/transports/soap_tests.py
  tests/transports/transport_tests.py
  tests/transports/xmlrpc_tests.py
  tools/requirements.txt
  tools/test-requirements.txt
Labels: Internal

#1637 Policy is not added when an AutoScale Group is created
  SoftLayer/CLI/autoscale/create.py
Labels: Bug

#1641 When `slcli event-log` not return any event log the command display an error
  SoftLayer/CLI/event_log/get.py
Labels: Bug

#1645 add new columns on vlan list(premium, tags)
  SoftLayer/CLI/vlan/list.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan.py
  SoftLayer/managers/network.py
Labels: CLI

#1646 Rich tables
  .github/workflows/tests.yml
  SoftLayer/CLI/call_api.py
  SoftLayer/CLI/core.py
  SoftLayer/CLI/dns/zone_import.py
  SoftLayer/CLI/environment.py
  SoftLayer/CLI/firewall/add.py
  SoftLayer/CLI/formatting.py
  SoftLayer/CLI/order/preset_list.py
  SoftLayer/CLI/virt/bandwidth.py
  SoftLayer/CLI/vpn/ipsec/configure.py
  SoftLayer/CLI/vpn/ipsec/detail.py
  SoftLayer/utils.py
  tests/CLI/environment_tests.py
  tests/CLI/helper_tests.py
  tests/CLI/modules/account_tests.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/call_api_tests.py
  tests/CLI/modules/file_tests.py
  tests/CLI/modules/ipsec_tests.py
  tests/CLI/modules/object_storage_tests.py
  tests/CLI/modules/order_tests.py
  tests/CLI/modules/server_tests.py
  tox.ini
Labels: CLI, Core

#1648 fixed documentation build issues
  SoftLayer/CLI/report/dc_closures.py
  SoftLayer/utils.py
  docs/cli/reports.rst
  docs/requirements.txt
Labels: Bug, Documentation

#1653 Improved successful response to command - slcli licenses cancel
  SoftLayer/CLI/licenses/cancel.py
Labels: New Feature

#1649 update the firewall list
  SoftLayer/CLI/firewall/list.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/firewall.py
  tests/CLI/modules/firewall_tests.py
  tests/managers/firewall_tests.py
Labels: CLI

#1656 Updated readme
  README.rst
Labels: Documentation

#1651 Update `slcli firewall detail` to handle multi vlan firewalls
  SoftLayer/CLI/firewall/detail.py
  SoftLayer/fixtures/SoftLayer_Network_Vlan_Firewall.py
  SoftLayer/managers/firewall.py
  tests/CLI/modules/firewall_tests.py
Labels: CLI
