Repository softlayer/softlayer-python, pull requests merged in 2022-12, with the labels that each got.

#1797 Version to 6.1.3
  .github/workflows/tests.yml
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release

#1801 Remove default filter on subnet list and fix the subnet detail
  SoftLayer/CLI/subnet/detail.py
  SoftLayer/managers/network.py
  tests/CLI/modules/account_tests.py
  tests/managers/network_tests.py
Labels: CLI

#1807 fixing issues with the auto build for releases
  .github/workflows/release.yml
Labels: Core

#1805 Improve subnet list
  SoftLayer/CLI/subnet/list.py
  SoftLayer/managers/network.py
Labels: New Feature

#1808 add a limit and sortby on data time on ticket list command on result …
  SoftLayer/CLI/ticket/list.py
  SoftLayer/managers/ticket.py
  tests/CLI/modules/ticket_tests.py
Labels: CLI

#1804 `slcli vs upgrade --resize-disk` is resizing another disk and not the selected one
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug
