Repository softlayer/softlayer-python, pull requests merged in 2022-07, with the labels that each got.

#1679 item-list fix
  SoftLayer/CLI/order/item_list.py
  tests/CLI/modules/order_tests.py
Labels: Bug

#1680 updating release job to actually publish to pypi
  .github/workflows/release.yml
Labels: Core

#1685 Update command - slcli object-storage endpoints
  SoftLayer/CLI/object_storage/list_endpoints.py
  SoftLayer/managers/object_storage.py
  tests/CLI/modules/object_storage_tests.py
  tests/managers/object_storage_tests.py
Labels: Bug

#1681 add the block volume-options command
  SoftLayer/CLI/block/options.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Location.py
  SoftLayer/managers/ordering.py
  docs/cli/block.rst
  tests/CLI/modules/block_tests.py
  tests/managers/ordering_tests.py
Labels: CLI

#1688 fixed issues where a message warned users about closing datacenter
  SoftLayer/CLI/hardware/create.py
  SoftLayer/CLI/order/place.py
  SoftLayer/CLI/virt/create.py
  SoftLayer/managers/network.py
  tests/CLI/modules/order_tests.py
  tests/CLI/modules/server_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
  tests/managers/network_tests.py
Labels: Bug

#1691 Update `slcli hardware sensor`
  SoftLayer/CLI/hardware/sensor.py
  SoftLayer/fixtures/SoftLayer_Hardware.py
Labels: Bug

#1695 Improved successful response to command - slcli vs cancel
  SoftLayer/CLI/virt/cancel.py
Labels: Bug

#1699 Added a dependabot scanner
  .github/dependabot.yml
Labels: Core

#1700 block|file volume-options improvements
  SoftLayer/CLI/block/options.py
  SoftLayer/CLI/file/options.py
Labels: Storage

#1703 Option create-options in commands hardware and dedicatedhost fixed
  SoftLayer/CLI/dedicatedhost/create_options.py
  SoftLayer/CLI/hardware/create_options.py
Labels: Bug

#1702 block/file volume-options improvements 2
  SoftLayer/CLI/block/options.py
  SoftLayer/CLI/file/options.py
Labels: CLI, Storage

#1698 New command ipsec order
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/vpn/ipsec/order.py
  SoftLayer/fixtures/SoftLayer_Product_Order.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/ipsec.py
  docs/cli/ipsec.rst
  tests/CLI/modules/ipsec_tests.py
  tests/managers/ipsec_tests.py
Labels: CLI, New Feature

#1705 block/file volume-options improvement 3
  SoftLayer/CLI/block/options.py
  SoftLayer/CLI/file/options.py
  SoftLayer/managers/ordering.py
Labels: CLI, Storage

#1707 Command slcli vlan create - displaying an error message
  SoftLayer/CLI/vlan/create.py
Labels: Bug

#1712 New Command: user device-access
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/device_access.py
  SoftLayer/fixtures/SoftLayer_User_Customer.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: CLI
