Repository softlayer/softlayer-python, pull requests merged in 2022-10, with the labels that each got.

#1762 add more information to vs credentials
  SoftLayer/CLI/virt/credentials.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  tests/CLI/modules/vs/vs_tests.py
Labels: CLI

#1765 Fixed maxint issue
  .github/workflows/release.yml
  SoftLayer/CLI/cdn/detail.py
  SoftLayer/fixtures/SoftLayer_Network_CdnMarketplace_Configuration_Mapping.py
  SoftLayer/fixtures/SoftLayer_Network_CdnMarketplace_Metrics.py
  tests/CLI/modules/cdn_tests.py
  tests/managers/cdn_tests.py
Labels: Bug

#1766 Added csv output format
  SoftLayer/CLI/core.py
  SoftLayer/CLI/formatting.py
  tests/CLI/modules/account_tests.py
  tests/CLI/modules/vs/vs_tests.py
Labels: New Feature

#1769 Delete twitter link in documentation
  docs/dev/index.rst
Labels: Bug, Documentation

#1774 new command hw create-credential
  SoftLayer/CLI/hardware/create_credential.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Hardware.py
  SoftLayer/fixtures/SoftLayer_Software_Component_Password.py
  SoftLayer/managers/hardware.py
  docs/cli/hardware.rst
  tests/CLI/modules/server_tests.py
  tests/managers/hardware_tests.py
Labels: CLI

#1781 fix the hw credential error
  SoftLayer/CLI/hardware/credentials.py
  SoftLayer/managers/hardware.py
  tests/CLI/modules/server_tests.py
Labels: CLI

#1784 Added test suite for py311
  SoftLayer/CLI/sshkey/add.py
  SoftLayer/transports/soap.py.unstable
  tests/transports/soap_tests.py.unstable
  tools/test-requirements.txt
  tox.ini
Labels: Core

#1775 New feature to change theme in slcli like dark, light o maintain in default
  SoftLayer/CLI/command.py
  SoftLayer/CLI/config/__init__.py
  SoftLayer/CLI/config/setup.py
  SoftLayer/CLI/config/show.py
  SoftLayer/CLI/core.py
  SoftLayer/CLI/environment.py
  SoftLayer/CLI/formatting.py
  SoftLayer/utils.py
  tests/CLI/modules/config_tests.py
Labels: New Feature

#1780 Match `virtual detail --prices` option with `hardware detail --prices` option
  SoftLayer/CLI/virt/detail.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug

#1782 Fixing preset-list pricing table
  CONTRIBUTING.md
  SoftLayer/CLI/command.py
  SoftLayer/CLI/order/preset_list.py
  SoftLayer/managers/ordering.py
  tests/CLI/modules/order_tests.py
Labels: Bug
