Repository softlayer/softlayer-python, pull requests merged in 2022-04, with the labels that each got.

#1609 updated number of updates in the command account event-detail
  SoftLayer/CLI/account/event_detail.py
Labels: Bug

#1599 Add an orderBy filter to slcli vlan list
  SoftLayer/managers/network.py
  tests/managers/network_tests.py
Labels: CLI

#1611 Add options to print a specific table in command slcli account events
  SoftLayer/CLI/account/events.py
Labels: New Feature

#1614 Update global ip assign/unassign to use new API
  SoftLayer/CLI/globalip/assign.py
  SoftLayer/fixtures/SoftLayer_Network_Subnet.py
  SoftLayer/managers/network.py
  tests/CLI/modules/globalip_tests.py
  tests/managers/network_tests.py
Labels: CLI

#1615 Ability to route/unroute subnets
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/subnet/route.py
  SoftLayer/managers/network.py
  docs/cli/subnet.rst
  tests/CLI/modules/subnet_tests.py
Labels: CLI, New Feature

#1617 Improved successful response to command - slcli account cancel-item
  SoftLayer/CLI/account/cancel_item.py
Labels: New Feature

#1621 Mishandling of domain and hostname data in `slcli account item-detail`
  SoftLayer/CLI/account/item_detail.py
Labels: Bug
