Repository softlayer/softlayer-python, pull requests merged in 2023-04, with the labels that each got.

#1896 Added new command - slcli cdn delete
  SoftLayer/CLI/cdn/delete.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_CdnMarketplace_Configuration_Mapping.py
  SoftLayer/managers/cdn.py
  docs/cli/cdn.rst
  tests/CLI/modules/cdn_tests.py
  tests/managers/cdn_tests.py
Labels: New Feature

#1899 slcli firewall detail multiVlan:14109 --credentials
  SoftLayer/CLI/firewall/detail.py
  tests/CLI/modules/firewall_tests.py
Labels: CLI

#1901 add a new option on account orders
  SoftLayer/CLI/account/orders.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/account.py
  tests/CLI/modules/account_tests.py
  tests/managers/account_tests.py
Labels: Ordering

#1907 Issues with block/file volume-details on some volumes
  SoftLayer/CLI/block/detail.py
  SoftLayer/CLI/file/detail.py
Labels: Storage

#1904 Need a command for slcli object-storage delete <storageId>
  SoftLayer/CLI/object_storage/cancel.py
  SoftLayer/CLI/routes.py
  docs/cli/object_storage.rst
  tests/CLI/modules/object_storage_tests.py
Labels: CLI

#1910 New Command: `slcli user vpn-password`
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/vpn_password.py
  SoftLayer/fixtures/SoftLayer_User_Customer.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: New Feature

#1912 Update `slcli user detail` to display if user has API key
  SoftLayer/CLI/user/detail.py
Labels: CLI

#1909 Fixed an issue with 'slcli event-log get'
  SoftLayer/CLI/event_log/get.py
  tests/CLI/modules/event_log_tests.py
  tests/CLI/modules/sshkey_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
Labels: Bug

#1923 #1922 added the slcli file to this repo
  .gitignore
  README.rst
  slcli
Labels: CLI
