Repository softlayer/softlayer-python, pull requests merged in 2023-01, with the labels that each got.

#1803 Improve subnet detail
  SoftLayer/CLI/subnet/detail.py
  SoftLayer/fixtures/SoftLayer_Network_Subnet.py
  SoftLayer/managers/network.py
Labels: CLI

#1811 Added example to slcli call-api
  SoftLayer/CLI/call_api.py
Labels: Bug

#1810 subnet route and subnet clear-route
  SoftLayer/CLI/subnet/route.py
Labels: CLI

#1814 `slcli vs notifications` is displaying a hardware description
  SoftLayer/CLI/virt/notifications.py
Labels: Bug

#1825 Added script to list all commands in slcli
  cliChecker/README.md
  cliChecker/checker.py
  cliChecker/output.txt
Labels: Documentation

#1818 New Command: `slcli user grant-access`
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/grant_access.py
  SoftLayer/fixtures/SoftLayer_User_Customer.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: New Feature

#1822 Fixes firewall cancel so it can properly do multiVlan firewalls
  SoftLayer/CLI/command.py
  SoftLayer/CLI/firewall/cancel.py
  SoftLayer/managers/firewall.py
  SoftLayer/utils.py
Labels: Bug

#1824 `user remove-access` is not displaying all removed device access and its help command displaying error message
  SoftLayer/CLI/user/remove_access.py
  tests/CLI/modules/user_tests.py
Labels: Bug

#1833 feature search
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/search.py
  SoftLayer/fixtures/SoftLayer_Search.py
  SoftLayer/managers/search.py
  docs/cli/commands.rst
  tests/CLI/modules/search_tests.py
  tests/managers/search_tests.py
Labels: CLI, New Feature

#1830 Added flag to command slcli account events --date-min
  SoftLayer/CLI/account/events.py
  SoftLayer/CLI/account/invoices.py
  SoftLayer/CLI/account/orders.py
  SoftLayer/managers/account.py
  SoftLayer/utils.py
Labels: New Feature
