Repository softlayer/softlayer-python, pull requests merged in 2023-06, with the labels that each got.

#1955 add a new column on ipAddress table subnet details
  SoftLayer/CLI/subnet/detail.py
Labels: CLI

#1963 Group bandwidth commands
  SoftLayer/CLI/bandwidth/__init__.py
  SoftLayer/CLI/bandwidth/pools.py
  SoftLayer/CLI/bandwidth/pools_detail.py
  SoftLayer/CLI/bandwidth/summary.py
  SoftLayer/CLI/routes.py
  docs/cli/account.rst
  docs/cli/bandwidth.rst
  docs/cli/reports.rst
  tests/CLI/modules/account_tests.py
  tests/CLI/modules/bandwidth_tests.py
  tests/CLI/modules/report_tests.py
Labels: CLI

#1973 #1968
  SoftLayer/fixtures/SoftLayer_Network_Vlan.py
  tests/CLI/modules/vlan_tests.py
Labels: New Feature

#1965 `slcli account billing-items --create` always return an empty table
  SoftLayer/managers/account.py
  tests/managers/account_tests.py
Labels: CLI

#1966 update the network vlan on hardware detail
  SoftLayer/CLI/hardware/detail.py
  SoftLayer/fixtures/SoftLayer_Hardware_Server.py
  SoftLayer/managers/hardware.py
Labels: CLI

#1974 Improve resolve ids functionality
  SoftLayer/utils.py
Labels: Core

#1994 Fix misspelling
  SoftLayer/CLI/config/setup.py
Labels: Bug

#1991 New command `slcli bandwidth pools-edit`
  SoftLayer/CLI/bandwidth/pools_edit.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Network_Bandwidth_Version1_Allotment.py
  SoftLayer/managers/bandwidth.py
  docs/cli/bandwidth.rst
  tests/CLI/modules/bandwidth_tests.py
Labels: New Feature

#1996 Error on hardware create with Operation system #1638
  SoftLayer/managers/ordering.py
  tests/managers/ordering_tests.py
Labels: Bug

#1999 LB protocol features
  SoftLayer/CLI/loadbal/protocol_add.py
  SoftLayer/CLI/loadbal/protocol_delete.py
  SoftLayer/CLI/loadbal/protocol_edit.py
  SoftLayer/CLI/routes.py
  SoftLayer/managers/load_balancer.py
  docs/cli/loadbal.rst
  tests/CLI/modules/loadbal_tests.py
  tests/managers/loadbal_tests.py
Labels: CLI

#2000 slcli bandwidth pools-create with single locations as option #1990
  SoftLayer/CLI/bandwidth/pools_create.py
  slcli
  tests/CLI/modules/bandwidth_tests.py
Labels: New Feature
