Repository softlayer/softlayer-python, pull requests merged in 2023-09, with the labels that each got.

#2086 v6.1.8 version bump
  SoftLayer/consts.py
  setup.py
Labels: Release

#2084 Added Example and some sub features in slcli file volume-cancel, slcli file volume-duplicate, slcli file volume-limits
  SoftLayer/CLI/file/cancel.py
  SoftLayer/CLI/file/duplicate.py
  SoftLayer/CLI/file/limit.py
  tests/CLI/modules/file_tests.py
Labels: CLI

#2089 PyPi publishing update
  .github/workflows/codeql-analysis.yml
  .github/workflows/documentation.yml
  .github/workflows/release.yml
  .github/workflows/test_pypi_release.yml
  .github/workflows/tests.yml
Labels: Core

#2090 fixed image detail object mask
  SoftLayer/CLI/image/__init__.py
Labels: Bug

#2091 added force feature for hardware poweron and poweroff
  SoftLayer/CLI/hardware/power.py
  tests/CLI/modules/server_tests.py
Labels: CLI

#2093 v6.1.9 version update
  SoftLayer/consts.py
  setup.py
Labels: Release

#2094 Implement IBM Detect-Secrets
  .pre-commit-config.yaml
  .secrets.baseline
  CONTRIBUTING.md
Labels: Core

#2096 Fixing sphinx-build issues
  CONTRIBUTING.md
  Makefile
  SoftLayer/CLI/bandwidth/pools_create.py
  docs/cli/bandwidth.rst
Labels: Documentation, Core

#2098 #2095 changed os version for readthedocs to a supported version
  .readthedocs.yml
Labels: Documentation

#2099 fixing build errors for documentation
  .readthedocs.yml
Labels: Documentation

#2100 Fixing readthedocs build
  .readthedocs.yml
Labels: Documentation

#2101 apparently style.css is a reserved word for sphinx/readthedocs
  CONTRIBUTING.md
  docs/_static/style.css
Labels: Documentation

#2102 updating requirements with specific versions
  docs/requirements.txt
Labels: Documentation
