Repository softlayer/softlayer-python, pull requests merged in 2023-03, with the labels that each got.

#1865 fixed an issue showing block/file snapshot prices
  SoftLayer/API.py
  SoftLayer/CLI/block/options.py
  SoftLayer/managers/ordering.py
  tests/CLI/modules/config_tests.py
Labels: Storage

#1868 `vs list --search` functionality
  SoftLayer/CLI/virt/list.py
  SoftLayer/managers/__init__.py
  SoftLayer/managers/search.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/search_tests.py
  tests/managers/vs/vs_tests.py
Labels: CLI

#1874 slcli hw list --search "query"
  SoftLayer/CLI/hardware/list.py
  SoftLayer/managers/search.py
  tests/CLI/modules/server_tests.py
Labels: CLI

#1878 new command account hooks
  SoftLayer/CLI/account/hooks.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/account.py
  docs/cli/account.rst
  tests/CLI/modules/account_tests.py
  tests/managers/account_tests.py
Labels: CLI

#1866 Updated command `slcli image detail`
  SoftLayer/CLI/image/__init__.py
  SoftLayer/CLI/image/detail.py
Labels: New Feature

#1861 New command `slcli image share`
  SoftLayer/CLI/image/share.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest_Block_Device_Template_Group.py
  SoftLayer/managers/image.py
  docs/cli/image.rst
  tests/CLI/modules/image_tests.py
  tests/managers/image_tests.py
Labels: New Feature

#1880 removed autoscale commands
  SoftLayer/CLI/autoscale/__init__.py
  SoftLayer/CLI/autoscale/delete.py
  SoftLayer/CLI/autoscale/detail.py
  SoftLayer/CLI/autoscale/list.py
  SoftLayer/CLI/routes.py
  SoftLayer/managers/autoscale.py
  docs/cli/autoscale.rst
  tests/CLI/modules/autoscale_tests.py
  tests/managers/autoscale_tests.py
Labels: CLI

#1882 Unable to determine file\block storage limits per datacenter
  SoftLayer/CLI/block/limit.py
  SoftLayer/CLI/file/limit.py
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  tests/CLI/modules/block_tests.py
  tests/CLI/modules/file_tests.py
Labels: Bug

#1881 Solved bug `slcli vs capture` Error: Got unexpected extra argument
  SoftLayer/CLI/virt/capture.py
Labels: Bug

#1886 New Command, account hook-create feature
  SoftLayer/CLI/account/hook_create.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Provisioning_Hook.py
  SoftLayer/managers/account.py
  docs/cli/account.rst
  tests/CLI/modules/account_tests.py
  tests/managers/account_tests.py
Labels: CLI, New Feature

#1890 Updated request to list all permissions to users
  SoftLayer/fixtures/SoftLayer_User_Permission_Action.py
  SoftLayer/managers/user.py
  tests/CLI/modules/user_tests.py
  tests/managers/user_tests.py
Labels: CLI

#1887 Dont fail when trying to get user information from slcli event-log get
  SoftLayer/CLI/event_log/get.py
Labels: Bug

#1891 Fix `slcli hardware create-credential` command
  SoftLayer/CLI/hardware/create_credential.py
  tests/CLI/modules/server_tests.py
Labels: Bug

#1892 new feature on account hook-delete
  SoftLayer/CLI/account/hook_delete.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Provisioning_Hook.py
  SoftLayer/managers/account.py
  docs/cli/account.rst
  tests/CLI/modules/account_tests.py
  tests/managers/account_tests.py
Labels: CLI, New Feature

#1893 v6.1.6 version
  CHANGELOG.md
  SoftLayer/consts.py
  setup.py
Labels: Release
