Repository softlayer/softlayer-python, pull requests merged in 2023-02, with the labels that each got.

#1843 slcli vs capture uses a deprecated API
  SoftLayer/CLI/virt/capture.py
  SoftLayer/fixtures/SoftLayer_Virtual_Guest.py
  SoftLayer/managers/vs.py
  tests/CLI/modules/vs/vs_tests.py
  tests/managers/vs/vs_tests.py
Labels: Bug

#1846 Updated command slcli block replica-order
  SoftLayer/CLI/block/replication/disaster_recovery_failover.py
  SoftLayer/CLI/block/replication/failback.py
  SoftLayer/CLI/block/replication/failover.py
  SoftLayer/CLI/block/replication/locations.py
  SoftLayer/CLI/block/replication/order.py
  SoftLayer/CLI/block/replication/partners.py
  SoftLayer/managers/storage.py
  SoftLayer/managers/storage_utils.py
  tests/CLI/modules/block_tests.py
  tests/managers/storage_utils_tests.py
Labels: New Feature

#1847 unexpected error when using vlan list with --limit 0 or 999 and a lar…
  SoftLayer/CLI/vlan/list.py
  SoftLayer/fixtures/SoftLayer_Account.py
  tests/CLI/modules/vlan_tests.py
Labels: Bug

#1835 New Command: `slcli virtual host-list`
  SoftLayer/CLI/core.py
  SoftLayer/CLI/dedicatedhost/list.py
  SoftLayer/CLI/hardware/reload.py
  SoftLayer/CLI/order/place.py
  SoftLayer/CLI/order/quote.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/storage_utils.py
  SoftLayer/CLI/virt/create.py
  SoftLayer/fixtures/SoftLayer_Account.py
  SoftLayer/managers/block.py
  SoftLayer/managers/dedicated_host.py
  SoftLayer/managers/file.py
  SoftLayer/managers/firewall.py
  SoftLayer/managers/storage_utils.py
  SoftLayer/managers/vs.py
  SoftLayer/transports/xmlrpc.py
  docs/cli/dedicated.rst
  docs/cli/vs.rst
  tests/CLI/modules/dedicatedhost_tests.py
  tests/managers/dedicated_host_tests.py
Labels: New Feature

#1832 update volume-refresh command
  SoftLayer/CLI/block/refresh.py
  SoftLayer/CLI/file/refresh.py
  SoftLayer/managers/storage.py
Labels: Storage

#1838 vs os-available command
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/virt/os_available.py
  SoftLayer/fixtures/SoftLayer_Product_Package.py
  SoftLayer/managers/vs.py
  docs/cli/vs.rst
  tests/CLI/modules/vs/vs_tests.py
Labels: CLI

#1850 New Command: `slcli virtual host-create`
  SoftLayer/CLI/routes.py
  docs/cli/dedicated.rst
  docs/cli/vs.rst
Labels: CLI, New Feature

#1840 `slcli block access`, updated some descriptions, change flag -h to -d, sort flags
  SoftLayer/CLI/autoscale/detail.py
  SoftLayer/CLI/autoscale/list.py
  SoftLayer/CLI/block/access/authorize.py
  SoftLayer/CLI/block/access/list.py
  SoftLayer/CLI/block/access/password.py
  SoftLayer/CLI/block/access/revoke.py
Labels: CLI

#1852 slcli vlan list only returns 100 results
  SoftLayer/managers/network.py
Labels: Bug

#1854 v6.1.4
  SoftLayer/consts.py
  setup.py
Labels: Release

#1855 removed snapcraft from publish build.
  .github/workflows/release.yml
Labels: Core

#1858 Updated command slcli block snapshot-order, added flag iops
  SoftLayer/CLI/block/snapshot/cancel.py
  SoftLayer/CLI/block/snapshot/create.py
  SoftLayer/CLI/block/snapshot/delete.py
  SoftLayer/CLI/block/snapshot/disable.py
  SoftLayer/CLI/block/snapshot/enable.py
  SoftLayer/CLI/block/snapshot/get_notify_status.py
  SoftLayer/CLI/block/snapshot/list.py
  SoftLayer/CLI/block/snapshot/order.py
  SoftLayer/CLI/block/snapshot/restore.py
  SoftLayer/CLI/block/snapshot/schedule_list.py
  SoftLayer/CLI/block/snapshot/set_notify_status.py
  SoftLayer/managers/storage.py
  SoftLayer/managers/storage_utils.py
  tests/CLI/modules/block_tests.py
  tests/managers/storage_utils_tests.py
Labels: New Feature

#1859 Fix email commands
  SoftLayer/CLI/email/detail.py
  SoftLayer/CLI/email/list.py
Labels: CLI
