Repository softlayer/softlayer-python, pull requests merged in 2023-05, with the labels that each got.

#1930 updates for v6.1.7
  SoftLayer/consts.py
  setup.py
Labels: Release

#1924 Added double quotes in CSV outputformat
  SoftLayer/CLI/formatting.py
  tests/CLI/modules/account_tests.py
  tests/CLI/modules/vs/vs_tests.py
Labels: Bug

#1929 add a new command on order items-cancelation
  SoftLayer/CLI/order/cancelation.py
  SoftLayer/CLI/routes.py
  SoftLayer/fixtures/SoftLayer_Billing_Item_Cancellation_Request.py
  SoftLayer/managers/ordering.py
  docs/cli/ordering.rst
  tests/CLI/modules/order_tests.py
  tests/managers/ordering_tests.py
Labels: CLI, New Feature

#1919 New Command: `slcli user apikey`
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/user/apikey.py
  SoftLayer/fixtures/SoftLayer_User_Customer.py
  SoftLayer/managers/user.py
  docs/cli/users.rst
  tests/CLI/modules/sshkey_tests.py
  tests/CLI/modules/user_tests.py
  tests/CLI/modules/vs/vs_create_tests.py
  tests/managers/user_tests.py
Labels: CLI

#1925 Add ability to filter in slcli account billing-items
  SoftLayer/CLI/account/billing_items.py
  SoftLayer/managers/account.py
  tests/CLI/modules/account_tests.py
Labels: CLI, New Feature

#1938 added unit test cases
  tests/CLI/modules/account_tests.py
Labels: New Feature

#1945 Added Unit Test Case and Fixture
  SoftLayer/fixtures/SoftLayer_Network_Storage.py
  tests/CLI/modules/block_tests.py
Labels: New Feature

#1932 Remove `bytes-used` from block volume-list
  SoftLayer/CLI/block/list.py
  tests/CLI/modules/block_tests.py
Labels: Bug

#1934 Updated command - slcli cdn purge
  SoftLayer/managers/cdn.py
  tests/managers/cdn_tests.py
Labels: Bug

#1941 add a limit default 100 to image list --public
  SoftLayer/managers/image.py
Labels: CLI

#1953 Updated command - slcli report bandwidth
  SoftLayer/CLI/formatting.py
  SoftLayer/CLI/report/bandwidth.py
  tests/CLI/modules/report_tests.py
Labels: New Feature

#1943 Updated command - slcli account bandwidth-pools
  SoftLayer/CLI/account/bandwidth_pools.py
  SoftLayer/managers/account.py
Labels: New Feature

#1950 Related this issue:#1744
  SoftLayer/CLI/virt/list.py
Labels: New Feature

#1951 New Command: `slcli security`
  SoftLayer/CLI/environment.py
  SoftLayer/CLI/routes.py
  SoftLayer/CLI/security/__init__.py
  SoftLayer/CLI/security/cert_add.py
  SoftLayer/CLI/security/cert_download.py
  SoftLayer/CLI/security/cert_edit.py
  SoftLayer/CLI/security/cert_list.py
  SoftLayer/CLI/security/cert_remove.py
  SoftLayer/CLI/security/sshkey_add.py
  SoftLayer/CLI/security/sshkey_edit.py
  SoftLayer/CLI/security/sshkey_list.py
  SoftLayer/CLI/security/sshkey_print.py
  SoftLayer/CLI/security/sshkey_remove.py
  docs/cli/security.rst
  docs/cli/sshkey.rst
  docs/cli/ssl.rst
  tests/CLI/modules/security_tests.py
  tests/CLI/modules/ssl_tests.py
Labels: CLI

#1958 Figure out why slcli vs list --tag <tagName> doesnt work properly
  SoftLayer/CLI/virt/list.py
Labels: Bug

#1960 Updated readthedocs documentation
  SoftLayer/CLI/search.py
  SoftLayer/managers/search.py
  SoftLayer/utils.py
  docs/api/managers/autoscale.rst
  docs/api/managers/search.rst
  docs/cli/commands.rst
  docs/cli/security.rst
  docs/cli/sshkey.rst
  docs/cli/ssl.rst
  docs/cli/vs.rst
  docs/dev/SoftLayer-Python.drawio
  docs/dev/index.rst
  docs/images/SoftLayer-Python.png
Labels: Documentation
