Repository softlayer/softlayer-python, pull requests merged in 2024-07, with the labels that each got.

#2162 Updated CodeQL Jobs
  .github/workflows/codeql-analysis.yml
Labels: Core

#2164 v6.2.3 version bump
  SoftLayer/consts.py
  setup.py
Labels: Core, Release

#2170 update requests
  README.rst
  setup.py
  tools/requirements.txt
  tools/test-requirements.txt
Labels: Core

#2171 Update codeql-analysis.yml to v3
  .github/workflows/codeql-analysis.yml
Labels: Core

#2173 V6.2.4 version bump
  SoftLayer/consts.py
  setup.py
Labels: Release

#2174 Added x509 certificate support to cli
  SoftLayer/API.py
  SoftLayer/config.py
Labels: CLI, Internal

#2175 v6.2.5 updates
  SoftLayer/consts.py
  setup.py
Labels: Release
